In [12]:
import pandas as pd


In [20]:
import numpy as np

In [2]:
pd.read_table('D:/prd/src/PRD/sku_input_data.txt', encoding='gb2312', delim_whitespace=True, index_col=0)

item_sku_id  subd_num  delv_center_num  store_num  \
sale_ord_id                                                      
70465578389      1000329         6              772         26   
70465578390      1004607         6              772         26   
70465578391      1024209         6              772         26   
70465578392      1029174         6              772         26   
70465578393      1029192         6              772         26   
70465578394      1029193         6              772         26   
70465578395      1031896         6              772         26   
70465578396      1032341         6              772         26   
70465578397      1032344         6              772         26   
70465578398      1034742         6              772         26   
70465578399      1034748         6              772         26   
70465578400      1035891         6              772         26   
70465578401      1059442         6              772         26   
70465578402      1069550         6              772         26   
70465578403      1069551         6              772         26   
70465578404      1072486         6              772         26   
70465578405      1072487         6              772         26   
70465578406      1081235         6              772         26   
70465578407      1089493         6              772         26   
70465578408      1097041         6              772         26   
70465578409      1109513         6              772         26   
70465578410      1122970         6              772         26   
70465578411      1132153         6              772         26   
70465578412      1133552         6              772         26   
70465578413      1134360         6              772         26   
70465578414      1138664         6              772         26   
70465578415      1138665         6              772         26   
70465578416      1144881         6              772         26   
70465578417      1145775         6              772         26   
70465578418      1145777         6              772         26   
...                  ...       ...              ...        ...   
70465580232       699883         6              772         26   
70465580233       699891         6              772         26   
70465580234       729778         6              772         26   
70465580235       737912         6              772         26   
70465580236       737913         6              772         26   
70465580237       737914         6              772         26   
70465580238       737915         6              772         26   
70465580239       737919         6              772         26   
70465580240       759880         6              772         26   
70465580241       783883         6              772         26   
70465580242       788271         6              772         26   
70465580243       799135         6              772         26   
70465580244       799143         6              772         26   
70465580245       836044         6              772         26   
70465580246       836046         6              772         26   
70465580247       845492         6              772         26   
70465580248       845497         6              772         26   
70465580249       871531         6              772         26   
70465580250       886042         6              772         26   
70465580251       891202         6              772         26   
70465580252       919449         6              772         26   
70465580253       958431         6              772         26   
70465580254       958435         6              772         26   
70465580255       982652         6              772         26   
70465580256       982806         6              772         26   
70465580257       982813         6              772         26   
70465580258       990863         6              772         26   
70465580259       990867         6              772  

In [13]:
skuData = pd.read_excel('D:/prd/src/PRD/sku_input_data.xls','Sheet1')

In [5]:
type(skuData['sale_ord_id'])

pandas.core.series.Series

In [25]:
sale_ord_id_list = (skuData['sale_ord_id']).tolist()

In [26]:
item_sku_id_list = (skuData['item_sku_id']).tolist()

In [32]:
combine_list = [sale_ord_id_list,item_sku_id_list]

In [39]:
a=[1,3]
b=[2,4]
c=[a,b]
import numpy as np
npd = np.c_[a,b]
for row in npd:
    print(row)

[1 2]
[3 4]


In [40]:
npd

array([[1, 2],
       [3, 4]])

In [14]:
skuData5 = skuData.head(5)
npskuData5=skuData5.as_matrix()
for row in npskuData5:
    print(row[0])

70465578389
70465578390
70465578391
70465578392
70465578393


In [ ]:
## 增加一列

In [23]:
cols = npskuData5[:,[14,15]]

In [21]:
cols_new = np.array([5,4,3,2,1])

In [26]:
cols_combine = np.c_[cols,cols_new]

In [27]:
cols_combine

array([[6609.32674332265, 43683200, 5],
       [6616.3696994651, 43776348, 4],
       [4931.53120237518, 24320000, 3],
       [2765.21246923269, 7646400, 2],
       [2997.17200040304, 8983040, 1]], dtype=object)

In [ ]:
# arr_list

In [28]:
arr_list = []

arr1 = np.array([3,4,5,1])
arr_list.append(arr1)
arr2 = np.array([8,7,2,1,3])
arr_list.append(arr2)

arr_list

[array([3, 4, 5, 1]), array([8, 7, 2, 1, 3])]

In [33]:
arr_list.append([6,3,2,5])

In [38]:
myarr = np.array(arr_list)

In [ ]:
#np的列乘以list

In [39]:
myarr2 = myarr[:,2]* myarr[:,3]

In [42]:
myarr2*[2,3]

array([10, 30])