In [205]:
import pandas as pd
import numpy as np

In [234]:
skuData = pd.read_excel('D:/prd/src/PRD/sku_input_data.xls','Sheet1')

In [217]:
skuData

sale_ord_id  item_sku_id  subd_num  delv_center_num  store_num  \
0     70465578389      1000329         6              772         26   
1     70465578390      1004607         6              772         26   
2     70465578391      1024209         6              772         26   
3     70465578392      1029174         6              772         26   
4     70465578393      1029192         6              772         26   
5     70465578394      1029193         6              772         26   
6     70465578395      1031896         6              772         26   
7     70465578396      1032341         6              772         26   
8     70465578397      1032344         6              772         26   
9     70465578398      1034742         6              772         26   
10    70465578399      1034748         6              772         26   
11    70465578400      1035891         6              772         26   
12    70465578401      1059442         6              772         26   
13    70465578402      1069550         6              772         26   
14    70465578403      1069551         6              772         26   
15    70465578404      1072486         6              772         26   
16    70465578405      1072487         6              772         26   
17    70465578406      1081235         6              772         26   
18    70465578407      1089493         6              772         26   
19    70465578408      1097041         6              772         26   
20    70465578409      1109513         6              772         26   
21    70465578410      1122970         6              772         26   
22    70465578411      1132153         6              772         26   
23    70465578412      1133552         6              772         26   
24    70465578413      1134360         6              772         26   
25    70465578414      1138664         6              772         26   
26    70465578415      1138665         6              772         26   
27    70465578416      1144881         6              772         26   
28    70465578417      1145775         6              772         26   
29    70465578418      1145777         6              772         26   
...           ...          ...       ...              ...        ...   
1843  70465580232       699883         6              772         26   
1844  70465580233       699891         6              772         26   
1845  70465580234       729778         6              772         26   
1846  70465580235       737912         6              772         26   
1847  70465580236       737913         6              772         26   
1848  70465580237       737914         6              772         26   
1849  70465580238       737915         6              772         26   
1850  70465580239       737919         6              772         26   
1851  70465580240       759880         6              772         26   
1852  70465580241       783883         6              772         26   
1853  70465580242       788271         6              772         26   
1854  70465580243       799135         6              772         26   
1855  70465580244       799143         6              772         26   
1856  70465580245       836044         6              772         26   
1857  70465580246       836046         6              772         26   
1858  70465580247       845492         6              772         26   
1859  70465580248       845497         6              772         26   
1860  70465580249       871531         6              772         26   
1861  70465580250       886042         6              772         26   
1862  70465580251       891202         6              772         26   
1863  70465580252       919449         6              772         26   
1864  70465580253       958431         6              772         26   
1865  70465580254       958435         6              772         26   
1866  70465580255       982652         6      

In [224]:
skuData.columns.values

array(['sale_ord_id', 'item_sku_id', 'subd_num', 'delv_center_num',
       'store_num', 'item_second_cate_cd', 'item_second_cate_name',
       'sum_qtty', 'out_qtty', 'out_wh_num_7d_full_band', 'calc_volume',
       'len', 'width', 'height', 'max_inv', 'max_v'], dtype=object)

In [202]:
#row5 = skuData.head(5)

In [219]:
skuData['out_wh_num_7d_full_band'] = skuData['out_wh_num_7d_full_band'].fillna('None value')

In [218]:
np.shape(skuData)

(1873, 16)

In [200]:
#row5.iloc[9]

sale_ord_id                70465578398
item_sku_id                    1034742
subd_num                             6
delv_center_num                    772
store_num                           26
item_second_cate_cd               1387
item_second_cate_name             香水彩妆
sum_qtty                            96
out_qtty                            25
out_wh_num_7d_full_band          ZZZZZ
calc_volume                     489375
len                                145
width                              135
height                              25
max_inv                         6854.2
max_v                         46980000
Name: 9, dtype: object

In [ ]:
#按照item_second_cate_cd分组，然后再按照out_wh_num_7d_full_band为第二分组，再按照out_qtty降序排列

In [220]:
arr = np.array([])
row5_group = skuData.groupby('item_second_cate_cd')
for group_name, group_eles in row5_group:
    print(group_name)
    group_2 = group_eles.groupby(by='out_wh_num_7d_full_band',sort=True)
    for group2_name, group2_eles in group_2:        
        print(group2_name)
        group2_eles = group2_eles.sort_values(by='out_qtty',ascending=False)
        print(group2_eles)
        if len(arr)==0:
            arr=group2_eles.as_matrix()
        else:
            arr = np.concatenate((arr,group2_eles.as_matrix()) )
    

1381
D
     sale_ord_id  item_sku_id  subd_num  delv_center_num  store_num  \
303  70465578692      2504661         6              772         26   

     item_second_cate_cd item_second_cate_name  sum_qtty  out_qtty  \
303                 1381                  面部护肤      2914      1671   

    out_wh_num_7d_full_band  calc_volume  len  width  height       max_inv  \
303                       D      1305375  177    125      59  61675.463111   

          max_v  
303  3803862750  
E
     sale_ord_id  item_sku_id  subd_num  delv_center_num  store_num  \
902  70465579291      4588917         6              772         26   

     item_second_cate_cd item_second_cate_name  sum_qtty  out_qtty  \
902                 1381                  面部护肤       533       352   

    out_wh_num_7d_full_band  calc_volume  len  width  height       max_inv  \
902                       E       405000   75     75      72  14692.344946   

         max_v  
902  215865000  
F
      sale_ord_id  item_sku_id  subd_

In [221]:
len(arr)

1873

In [222]:
arr

array([[70465578692, 2504661, 6, ..., 59, 61675.4631113541, 3803862750],
       [70465579291, 4588917, 6, ..., 72, 14692.344945583, 215865000],
       [70465579362, 4712408, 6, ..., 40, 5280.0, 27878400],
       ..., 
       [70465580027, 6043145, 6, ..., 17, 2727.9882697695, 7441920],
       [70465579029, 4080245, 6, ..., 5, 4583.01210995563, 21004000],
       [70465580072, 6130884, 6, ..., 43, 2624.28656971756, 6886880]], dtype=object)

In [227]:
#保存到csv文件
config_pd = pd.DataFrame(arr,
                        columns =skuData.columns.values)
config_pd.to_csv('D:\sku_data_sort.csv',encoding='utf-8')

In [229]:
type(arr[:,15][0])

int

In [230]:
xi_arr = np.repeat(1.0, 500, axis=None)

In [233]:
count_sku = arr[0:500]
count_sku[:,15]

array([3803862750, 215865000, 27878400, 34836480, 1428908032, 43253760,
       45614400, 6336824, 42300000, 331652640, 128578320, 125452800,
       120384836, 390196800, 551388600, 109442740, 142565760, 222614700,
       234594800, 85141440, 247130400, 215961600, 157745280, 157313520,
       120294720, 113702400, 117625960, 178330328, 9576000, 86165600,
       213213000, 218477600, 187159392, 154885080, 359884800, 191089592,
       25920000, 145512000, 174915840, 104332800, 179481600, 234748800,
       25200000, 230480640, 364953600, 28800000, 364953600, 18240000,
       91353600, 129548544, 126738432, 4623345000, 877744000, 505751400,
       272312832, 47749501800, 47749501800, 47749501800, 261928800,
       261928800, 3133694304, 514755000, 781919556, 6396681732, 6396681732,
       6396681732, 6396681732, 159439950, 3912536320, 1354128720,
       821250000, 183699296, 219938004, 3271158000, 5078775240, 772137600,
       548730000, 532639800, 1295212800, 487816000, 70886400, 37642158,

In [ ]:
#np.c_默认按照列扩

In [167]:
arr1 = np.array([[1,3]])
arr2 = np.array([[4,5]])
np.concatenate((arr1,arr2))

array([[1, 3],
       [4, 5]])

In [175]:
type(arr)

numpy.ndarray

In [143]:
# pandas排序API的Demo

In [145]:
#构造DataFrame
frame=pd.DataFrame([[2,4,1,5],[3,1,4,5],[5,1,4,2]],columns=['b','a','d','c'],index=['one','two','three'])  

In [146]:
frame

b  a  d  c
one    2  4  1  5
two    3  1  4  5
three  5  1  4  2

In [14]:
#coding=utf-8  
import pandas as pd  
import numpy as np  
#以下实现排序功能。  
series=pd.Series([3,4,1,6],index=['b','a','d','c'])  
frame=pd.DataFrame([[2,4,1,5],[3,1,4,5],[5,1,4,2]],columns=['b','a','d','c'],index=['one','two','three'])  
print(frame)  
print(series)  

#series的排序API
print('series通过索引进行排序：')  
print(series.sort_index())  
print('series通过值进行排序:')  
print(series.sort_values())  

#dataframe的排序API

print('dataframe根据行索引进行降序排序（排序时默认升序，调节ascending参数）：')  
print(frame.sort_index(ascending=False))  
print('dataframe根据列索引进行排序：')  
print(frame.sort_index(axis=1))  
print('dataframe根据值进行排序：')  
print(frame.sort_values(by='a'))  
print('通过多个索引进行排序：')  
print(frame.sort_values(by=['a','c'])) 

       b  a  d  c
one    2  4  1  5
two    3  1  4  5
three  5  1  4  2
b    3
a    4
d    1
c    6
dtype: int64
series通过索引进行排序：
a    4
b    3
c    6
d    1
dtype: int64
series通过值进行排序:
d    1
b    3
a    4
c    6
dtype: int64
dataframe根据行索引进行降序排序（排序时默认升序，调节ascending参数）：
       b  a  d  c
two    3  1  4  5
three  5  1  4  2
one    2  4  1  5
dataframe根据列索引进行排序：
       a  b  c  d
one    4  2  5  1
two    1  3  5  4
three  1  5  2  4
dataframe根据值进行排序：
       b  a  d  c
two    3  1  4  5
three  5  1  4  2
one    2  4  1  5
通过多个索引进行排序：
       b  a  d  c
three  5  1  4  2
two    3  1  4  5
one    2  4  1  5


In [10]:
print('通过多个索引进行排序：')  
print(frame.sort_values(by=['a','c'])) 

通过多个索引进行排序：
       b  a  d  c
three  5  1  4  2
two    3  1  4  5
one    2  4  1  5


In [17]:
frame['c']

one      5
two      5
three    2
Name: c, dtype: int64

In [19]:
print(frame)

       b  a  d  c
one    2  4  1  5
two    3  1  4  5
three  5  1  4  2


In [37]:
df = pd.DataFrame({'key1': ['a', 'a', 'b', 'b', 'a'],
                'key2': ['one', 'two', 'one', 'two', 'one'],
                'data1': np.random.randn(5),
                'data2': np.random.randn(5)})


         data1     data2
key1                    
a    -0.256525  0.457246
b     1.838816 -0.659873


In [142]:
frame

b  a  d  c
one    2  4  1  5
two    3  1  4  5
three  5  1  4  2