In [1]:
#测试numpy的访问和索引
import numpy as np

In [4]:
data = np.random.randn(6,4)
data

array([[ 0.36904152, -1.16436841,  0.10956388, -0.09934152],
       [-0.02068708,  0.94527049,  0.54122425,  2.05152305],
       [-0.60218926, -0.49039126, -0.9688391 ,  0.7415128 ],
       [-1.77216221,  0.19176606,  0.42643017, -0.07936587],
       [ 2.1166997 ,  0.47099075,  0.42153277,  0.4740061 ],
       [-0.36142876,  0.30768288, -0.10236012,  0.91719556]])

In [5]:
#第2行的最后一个元素
data[1,-1]

2.0515230458172016

In [6]:
#第2行的除去最后一个元素的所有元素
data[1,:-1]

array([-0.02068708,  0.94527049,  0.54122425])

In [8]:
#第2行的切片间隔（步长）为2的获取元素
data[1,0:3:2]

array([-0.02068708,  0.54122425])